### DISCUSSION TITLE
友人

### DISCUSSION THREAD

**Discussion by giscus** [youngjunning/blog.zisheng.pro#93] [Announcements]
# 友人

有朋自网线来，不亦说乎。

https://youngjuning.js.org/friends/

**Comment by maxchang3** [comment]
你好~ 我已经添加你的地址到我的站点啦~ 在这边回你下~
```yaml
- name: 张麦麦的博客
  link: https://zhangmaimai.com
  avatar: https://zhangmaimai.com/favicon.ico
  descr: 我的影子想要去飞翔，我的人还在地上。
```

**Reply by youngjunning** [reply]
收到，这就安排

**Comment by pandalabme** [comment]
{
  "name": "熊猫实验室",
  "link": "https://pandalab.me/",
  "avatar": "https://cdn.jsdelivr.net/gh/pandalabme/blogImages@main/panda_banboo.jpg",
  "descr": "panda panda patapon"
}

**Comment by maxchang3** [comment]
Hi，站点信息已经更新~麻烦同步一下：

```yaml
- name: 张麦麦
  link: https://maxchang.me
  avatar: https://maxchang.me/favicon.svg
  descr: 我的影子想要去飞翔，我的人还在地上。
```
