### ISSUE TITLE
hexo-helper-live2d

### ISSUE THREAD

**Issue by youngjuning** [youngjunning/blog.zisheng.pro#116]
```sh
$ yarn add hexo-helper-live2d live2d-widget-model-miku
```
```yml
# https://imbhj.com/599f1d72/
live2d:
  enable: false
  scriptFrom: jsdelivr
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  debug: false
  model:
    use: live2d-widget-model-miku
  display:
    position: left
    width: 200
    height: 400
  mobile:
    show: false
```
